# Generated by Django 5.0.3 on 2024-05-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_delete_application_remove_allocation_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bursaryapplication",
            name="institution",
        ),
    ]
