# Generated by Django 5.0.3 on 2024-05-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_remove_bursaryapplication_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="bursaryapplication",
            name="institution",
            field=models.CharField(default="Unknown Institution", max_length=100),
        ),
    ]
